
dependencies:
- biopython=1.67=np111py34_0
- boto=2.42.0=py34_0
- bz2file=0.98=py34_0
- gensim=0.12.4=np111py34_0
- mkl=11.3.3=0
- nltk=3.2.1=py34_0
- numpy=1.11.1=py34_0
- openssl=1.0.2h=1
- pip=8.1.2=py34_0
- python=3.4.5=0
- readline=6.2=2
- requests=2.11.1=py34_0
- scipy=0.18.1=np111py34_0
- scikit-learn=0.18=np111py34_0
- setuptools=26.1.1=py34_0
- simplejson=3.8.2=py34_0
- six=1.10.0=py34_0
- smart_open=1.3.4=py34_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py34_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pandas
- python-dateutil